### PR TITLE
WIP: airflow java client

### LINKED ISSUE #17362: Implementing Open API client for JVM based languages
**Description**

Similar to [airflow-client-python](https://github.com/apache/airflow-client-python),
we should have a client for JVM based languages (Java/Scala/Kotlin)

We will generate and maintain a stable version of Api Client in a repository 
[airflow-client-java](https://github.com/apache/airflow-client-java)

Although, using OpenAPI Specs user is able to generate API Client themselves, 
but there might be some issues that needed to be fixed, which the community will be able to fix and provide users the seamless import and usage of clients.

**Are you willing to submit a PR?**
YES

### PR DESCRIPTION
**Pull request by pateash**
closes [airflow#17362](https://github.com/apache/airflow/issues/17362)

Some of the issues, I was getting couple of months back seems to be resolved with new OpenAPI version.

### CODE REVIEW

**Comment by potiuk** [comment]
Hard to review... Does it work? Should you remove WIP?

**Comment by pateash** [comment]
> Hard to review... Does it work? Should you remove WIP?

Not yet, 
there are still some pending issue with OpenAPI.
some of the calls are not working properly yet.
we will have to wait until those are also resolved.

**Comment by potiuk** [comment]
@pateash - can we cound on getting this one ready for review when the issues are solved?

**Comment by harry1989** [comment]
@potiuk I'm interested in this MR, we need this SDK to integrate with our applications,I'm willing to contribute, please let me know if there is anything that I can assist with.

**Comment by potiuk** [comment]
I think if you need it, it will be likely better if you just generate it yourself. I think we are not going to release the Java client officially as we have no expertise in Java - and we do not want to spend time maintaining it and fixing problems (we have a lot of problems with golang client). We will likely only release Python client in the future. 

But if you want to generate your own java client - feel free. There are likely some good generators you can use from our Open API specification.

**Comment by pateash** [comment]
@harry1989 this is blocked for openapi side.
I will check if the issues have been resolved and update here.

**Pull request closed without merging**
